name: Server testing workflow

on:

  push:

    branches:

      - main

jobs:

  Testing:

    runs-on: ubuntu-latest

    steps:

      - name: Checking out the application code
        uses: actions/checkout@v2

      - name: setting up python environment
        uses: actions/setup-python@v2

      - name: Installing dependencies

        run: |

          python -m pip install --upgrade pip

          pip install -r requirements.txt

      - name: Testing the application

        run: python -m unittest discover