name: server container workflow

on:

  push:

    branches:

      - main

jobs:

  Container-Building:

    runs-on: ubuntu-latest

    steps:

      - name: Checking out the application code

        uses: actions/checkout@v2

      - name: Building the application containers

        run: |

          echo 'Smoke test!'

